Traewelldroid/traewelldroid

app/build.gradle
app/src/main/java/de/hbch/traewelling/ui/main/MainActivity.kt
app/src/main/java/de/hbch/traewelling/ui/settings/SettingsFragment.kt
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

(The font for Fluent Emoji is a bit broken at the moment and will not work for emojis with skin-tones and the paperclip(py) emoji)

Add emoji picker to settings

---

app/src/main/java/de/hbch/traewelling/api/models/trip/HafasTrainTripStation.kt
app/src/main/res/layout/travel_stop_list_item.xml

Fixes #40 
Related https://github.com/Traewelling/traewelling/pull/1093

Fix issue with last stop of premature ending train being marked as cancelled

---

app/src/main/java/de/hbch/traewelling/adapters/ConnectionAdapter.kt

https://twitter.com/SchlaumeierTVDE/status/1589180588749385728

Use yellow instead of red for delays <5 minutes

---

app/src/main/res/layout/activity_info.xml
app/src/main/res/values/strings.xml

added version text to InfoActivity

---

app/src/main/java/de/hbch/traewelling/adapters/TravelStopAdapter.kt
app/src/main/res/layout/travel_stop_list_item.xml

This PR adds the use of the three different delay colors in the view of destination selection

💄 Added use of different delay color for smaller delays

---

app/src/main/java/de/hbch/traewelling/api/models/user/User.kt
app/src/main/java/de/hbch/traewelling/shared/UserViewModel.kt
app/src/main/java/de/hbch/traewelling/ui/checkIn/CheckInFragment.kt

Depending on https://github.com/Traewelling/traewelling/pull/1196

✨ Use default status visibility for check-ins

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/de/hbch/traewelling/adapters/ConnectionAdapter.kt
app/src/main/java/de/hbch/traewelling/adapters/DataBindingAdapters.kt
app/src/main/java/de/hbch/traewelling/adapters/TravelStopAdapter.kt
app/src/main/java/de/hbch/traewelling/shared/EventViewModel.kt
app/src/main/java/de/hbch/traewelling/shared/UserViewModel.kt
app/src/main/java/de/hbch/traewelling/ui/checkIn/CheckInFragment.kt
app/src/main/java/de/hbch/traewelling/ui/info/InfoActivity.kt
app/src/main/java/de/hbch/traewelling/ui/legal/LegalActivity.kt
app/src/main/java/de/hbch/traewelling/ui/main/MainActivity.kt
app/src/main/res/xml/backup_rules.xml
app/src/main/res/xml/locales_config.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Bump Kotlin, Gradle and dependencies
- Support Android 13 language picker
- Fix outdated backup config
- Fix compiler warnings

⬆️🧑‍💻 Cleanup

---

app/src/main/res/layout/fragment_select_destination.xml

Adds spacing to bottom of loading view in destination selection
fixes #76

💄 Improved destination selection loading layout

---

app/src/main/java/de/hbch/traewelling/adapters/DataBindingAdapters.kt
app/src/main/java/de/hbch/traewelling/api/models/trip/HafasLine.kt

:bug: Fixed crash on missing Hafas operator

---

app/src/main/java/de/hbch/traewelling/api/models/statistics/PersonalStatistics.kt
app/src/main/java/de/hbch/traewelling/ui/statistics/StatisticsFragment.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:bug: Display default text on missing operator name in statistics

---

app/src/main/java/de/hbch/traewelling/api/models/statistics/PersonalStatistics.kt
app/src/main/java/de/hbch/traewelling/api/models/status/Status.kt
app/src/main/java/de/hbch/traewelling/ui/statistics/StatisticsFragment.kt
app/src/main/res/layout/fragment_statistics.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:sparkles: added statistics for travel purposes

---

app/build.gradle
app/src/main/java/de/hbch/traewelling/adapters/DataBindingAdapters.kt
app/src/main/java/de/hbch/traewelling/api/ApiService.kt
app/src/main/java/de/hbch/traewelling/api/models/user/User.kt
app/src/main/java/de/hbch/traewelling/shared/UserViewModel.kt
app/src/main/java/de/hbch/traewelling/ui/user/AbstractUserFragment.kt
app/src/main/java/de/hbch/traewelling/ui/user/LoggedInAbstractUserFragment.kt
app/src/main/java/de/hbch/traewelling/ui/user/UserFragment.kt
app/src/main/res/drawable/ic_add_person.xml
app/src/main/res/drawable/ic_hourglass.xml
app/src/main/res/drawable/ic_person_remove.xml
app/src/main/res/layout/fragment_user.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

This PR adds a follow/unfollow button to the user profile view and closes #54

:sparkles: Add follow button

---

app/src/main/java/de/hbch/traewelling/adapters/CheckInAdapter.kt
app/src/main/java/de/hbch/traewelling/ui/user/AbstractUserFragment.kt
app/src/main/java/de/hbch/traewelling/ui/user/LoggedInAbstractUserFragment.kt
app/src/main/java/de/hbch/traewelling/ui/user/UserFragment.kt
app/src/main/res/navigation/bottom_navigation.xml

:sparkles: Search connections from user profile

---

app/src/main/java/de/hbch/traewelling/api/models/status/CheckIn.kt
app/src/main/java/de/hbch/traewelling/shared/CheckInViewModel.kt
app/src/main/java/de/hbch/traewelling/ui/checkIn/AbstractCheckInFragment.kt
app/src/main/res/drawable/ic_chain.xml
app/src/main/res/layout/fragment_check_in.xml

:sparkles: Add chain toot feature

---

app/src/main/java/de/hbch/traewelling/adapters/TravelStopAdapter.kt

:bug: Fix color of last stop of journey

---

app/src/main/java/de/hbch/traewelling/adapters/DataBindingAdapters.kt
app/src/main/java/de/hbch/traewelling/api/ApiService.kt
app/src/main/java/de/hbch/traewelling/api/models/user/User.kt
app/src/main/java/de/hbch/traewelling/shared/UserViewModel.kt
app/src/main/res/drawable/ic_mute.xml
app/src/main/res/drawable/ic_unmute.xml
app/src/main/res/layout/fragment_user.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:sparkles: Add mute button to profile

---

app/src/main/java/de/hbch/traewelling/api/ApiService.kt
app/src/main/java/de/hbch/traewelling/ui/selectDestination/SelectDestinationViewModel.kt

https://github.com/Traewelling/traewelling/pull/1275

:alien: Update ApiService to represent breaking API changes

---

app/src/main/java/de/hbch/traewelling/api/ApiService.kt

See: https://github.com/Traewelling/traewelling/issues/1317#issuecomment-1403680071

Use new mute endpoint

---

app/src/main/java/de/hbch/traewelling/ui/include/cardSearchStation/SearchStationCard.kt
app/src/main/java/de/hbch/traewelling/ui/include/status/CardCheckInOverview.kt
app/src/main/res/drawable/ic_more.xml
app/src/main/res/layout/card_checkin_overview.xml

:lipstick: Move status delete/edit button to a popup menu

---

app/src/main/java/de/hbch/traewelling/ui/statusDetail/StatusDetailFragment.kt
app/src/main/res/layout/fragment_status_detail.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:lipstick: Add error screen for status detail if it is invisible

---

app/src/main/java/de/hbch/traewelling/ui/login/LoginActivity.kt

:passport_control: Disallow Firefox for OAuth login

---

app/src/main/java/de/hbch/traewelling/ui/checkIn/CheckIn.kt

:ambulance: Fix hopping cursor in status message field

---

app/src/main/java/de/hbch/traewelling/ui/include/status/CheckInCard.kt

:bug: Fix weird like state

---

app/src/main/java/de/hbch/traewelling/api/dtos/TripStation.kt
app/src/main/java/de/hbch/traewelling/api/models/trip/HafasTrainTripStation.kt
app/src/main/java/de/hbch/traewelling/ui/checkIn/CheckIn.kt
app/src/main/java/de/hbch/traewelling/ui/selectDestination/AbstractSelectDestinationFragment.kt
app/src/main/java/de/hbch/traewelling/ui/selectDestination/SelectDestination.kt

:bug: Fix displayed stations on ring line journeys

---

app/src/main/java/de/hbch/traewelling/api/dtos/Status.kt
app/src/main/java/de/hbch/traewelling/api/models/status/Journey.kt
app/src/main/java/de/hbch/traewelling/api/models/status/Status.kt
app/src/main/java/de/hbch/traewelling/ui/include/status/CheckInCard.kt

closes #121 when Traewelling/traewelling#1704 is merged

:sparkles: Display journey number on CheckInCard

---

app/src/main/java/de/hbch/traewelling/navigation/NavHost.kt

:bug: Fix default status visibility

---

app/src/main/java/de/hbch/traewelling/theme/Colors.kt
app/src/main/java/de/hbch/traewelling/theme/TraewelldroidTheme.kt
app/src/main/java/de/hbch/traewelling/ui/statusDetail/StatusDetail.kt

:bug: Fix visibility of polyline on dark themes

---

app/src/main/java/de/hbch/traewelling/shared/SharedValues.kt
app/src/main/java/de/hbch/traewelling/ui/composables/Map.kt
app/src/main/java/de/hbch/traewelling/ui/settings/Settings.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:sparkles: Add OpenRailwayMap layer selection

---

app/src/main/java/de/hbch/traewelling/api/models/notifications/Notification.kt
app/src/main/java/de/hbch/traewelling/api/models/notifications/NotificationData.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:sparkles: Implement MastodonNotShared notification

---

app/src/main/java/de/hbch/traewelling/ui/notifications/Notifications.kt

:sparkles: Mark notification as read when opened

---

app/src/main/java/de/hbch/traewelling/navigation/NavHost.kt

:bug: Fix backward destination selection on status edit

---

app/src/main/java/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/java/de/hbch/traewelling/shared/CheckInViewModel.kt
app/src/main/java/de/hbch/traewelling/ui/main/MainActivity.kt
app/src/main/java/de/hbch/traewelling/util/Extensions.kt

:children_crossing: Better back stack handling on check-in

---

app/src/main/java/de/hbch/traewelling/api/ApiService.kt
app/src/main/java/de/hbch/traewelling/ui/include/cardSearchStation/CardSearchStation.kt
app/src/main/java/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt
app/src/main/java/de/hbch/traewelling/ui/searchConnection/SearchConnectionViewModel.kt

:children_crossing: Fix purged trips by improving filtering

---

app/src/main/java/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/java/de/hbch/traewelling/shared/CheckInViewModel.kt
app/src/main/java/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt

:lipstick: Fix product icon on CheckIn view

---

app/src/main/java/de/hbch/traewelling/adapters/ZonedDateTimeGsonConverter.kt
app/src/main/java/de/hbch/traewelling/api/ApiService.kt
app/src/main/java/de/hbch/traewelling/api/models/status/UpdateStatusRequest.kt
app/src/main/java/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/java/de/hbch/traewelling/shared/CheckInViewModel.kt
app/src/main/java/de/hbch/traewelling/shared/FeatureFlags.kt
app/src/main/java/de/hbch/traewelling/ui/checkIn/CheckIn.kt
app/src/main/java/de/hbch/traewelling/ui/composables/ManualDateTimeSelection.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:sparkles: Manual overwrite of journey times

---

app/src/main/java/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt

:bug: Fix London trains (trains without line name)

---

app/src/main/kotlin/de/hbch/traewelling/api/models/status/StatusPoints.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/ui/checkInResult/CheckInResult.kt
app/src/main/kotlin/de/hbch/traewelling/ui/composables/DataLoading.kt
app/src/main/kotlin/de/hbch/traewelling/ui/composables/Switch.kt
app/src/main/kotlin/de/hbch/traewelling/ui/login/LoginActivity.kt
app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt
app/src/main/res/values/strings.xml

- Add Share button to check-in result screen
- Share status body in share text if existing

:sparkles: Improve share experience

---

app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt

:sparkles: Add share option to card menu

---

app/src/main/kotlin/de/hbch/traewelling/ui/statistics/DailyStatistics.kt

:sparkles: Add daily statistics date selection

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/kotlin/de/hbch/traewelling/TraewelldroidApplication.kt
app/src/main/kotlin/de/hbch/traewelling/api/models/status/Journey.kt
app/src/main/kotlin/de/hbch/traewelling/shared/FeatureFlags.kt
app/src/main/kotlin/de/hbch/traewelling/ui/statusDetail/StatusDetail.kt

:triangular_flag_on_post: Add display of operator

---

.gitignore
app/build.gradle
app/src/main/kotlin/de/hbch/traewelling/api/ApiService.kt
app/src/main/kotlin/de/hbch/traewelling/ui/info/Info.kt
app/src/main/kotlin/de/hbch/traewelling/ui/info/InfoActivity.kt
app/src/main/kotlin/de/hbch/traewelling/ui/main/MainActivity.kt
build.gradle

- migrate to a FOSS lib to display lib licenses (like opposed in #36)
- create flavors for devices with/without google services

:building_construction: Preparation for future

---

app/src/main/kotlin/de/hbch/traewelling/shared/FeatureFlags.kt
app/src/main/kotlin/de/hbch/traewelling/ui/statusDetail/StatusDetail.kt

:triangular_flag_on_post: Remove EVU display flag

---

app/src/main/kotlin/de/hbch/traewelling/ui/login/LoginActivity.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:ambulance: Display error on Firefox devices

---

app/src/main/kotlin/de/hbch/traewelling/api/models/trip/HafasLine.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt

:sparkles: Display journey number on search

---

app/build.gradle

:heavy_minus_sign: Ban Sentry from FOSS build

---

app/src/main/kotlin/de/hbch/traewelling/api/models/status/Status.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt
app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt

This is about to honour the appearance of @Traewelling on the ZDF.
#LassDichÜberwachen

:egg: Knackige Pfirsiche.

---

app/src/main/kotlin/de/hbch/traewelling/ui/settings/Settings.kt

:bug: Update line icon timestamp after refresh

---

app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt

:bug: Fix visibility of status when editing

---

app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt

:bug: Fix disappearing menu items

---

app/src/main/kotlin/de/hbch/traewelling/api/models/trip/HafasLine.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt

:ambulance: Make line name nullable

---

app/build.gradle
app/src/foss/kotlin/de/hbch/traewelling/logging/Logger.kt
app/src/foss/kotlin/de/hbch/traewelling/util/ReviewRequest.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/shared/SharedValues.kt
app/src/main/kotlin/de/hbch/traewelling/ui/checkInResult/CheckInResult.kt
app/src/main/kotlin/de/hbch/traewelling/util/IReviewRequest.kt
app/src/play/kotlin/de/hbch/traewelling/logging/Logger.kt
app/src/play/kotlin/de/hbch/traewelling/util/ReviewRequest.kt

:sparkles: Add review request for Play users

---

app/src/main/kotlin/de/hbch/traewelling/api/models/user/User.kt
app/src/main/kotlin/de/hbch/traewelling/ui/user/User.kt

:alien: Calculate displayed average velocity

---

app/src/main/kotlin/de/hbch/traewelling/ui/login/LoginActivity.kt

:ambulance: Fix auto logout

---

app/src/main/kotlin/de/hbch/traewelling/api/models/status/Status.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt

:bug: Hide favs when user did disable them

---

app/src/main/kotlin/de/hbch/traewelling/api/models/user/User.kt
app/src/main/kotlin/de/hbch/traewelling/ui/user/User.kt
app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt

:sparkles: Add link to Mastodon profile if connected

---

app/src/main/kotlin/de/hbch/traewelling/api/models/notifications/Notification.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:bug: Fix buggy Mastodon error notifications

---

app/src/main/AndroidManifest.xml

:coffin: Remove cleartext traffic

---

app/src/main/kotlin/de/hbch/traewelling/api/models/trip/HafasLine.kt
app/src/main/res/drawable/ic_taxi.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:sparkles: Add product type for taxi

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/de/hbch/traewelling/api/ApiService.kt
app/src/main/kotlin/de/hbch/traewelling/api/models/status/Status.kt
app/src/main/kotlin/de/hbch/traewelling/api/models/status/UserMention.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/shared/BottomSearchViewModel.kt
app/src/main/kotlin/de/hbch/traewelling/ui/checkIn/CheckIn.kt
app/src/main/kotlin/de/hbch/traewelling/ui/dashboard/Dashboard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/cardSearchStation/CardSearch.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/main/MainActivity.kt
app/src/main/kotlin/de/hbch/traewelling/ui/search/Search.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt
app/src/main/kotlin/de/hbch/traewelling/ui/statusDetail/StatusDetail.kt
app/src/main/kotlin/de/hbch/traewelling/ui/user/Profile.kt
app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

When users are mentioned in a check-in, the profile can be opened by clicking the mention:
When checking in, a user can be mentioned by typing the username or searching when typing:

:sparkles: Add user mentions

---

app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt

:sparkles: Add #NowTräwelling to share text

---

app/src/main/kotlin/de/hbch/traewelling/ui/settings/Settings.kt

:children_crossing: Clarify travelynx token

---

app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/shared/BottomSearchViewModel.kt
app/src/main/kotlin/de/hbch/traewelling/ui/checkIn/CheckIn.kt
app/src/main/kotlin/de/hbch/traewelling/ui/dashboard/Dashboard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/cardSearchStation/CardSearch.kt
app/src/main/kotlin/de/hbch/traewelling/ui/main/MainActivity.kt
app/src/main/kotlin/de/hbch/traewelling/ui/search/Search.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt

:recycle: Move user mention search to CheckIn

---

app/src/main/kotlin/de/hbch/traewelling/api/ApiService.kt
app/src/main/kotlin/de/hbch/traewelling/api/models/station/Station.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/Destinations.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/ui/dashboard/Dashboard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/cardSearchStation/CardSearch.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/search/Search.kt
app/src/main/kotlin/de/hbch/traewelling/ui/search/SearchViewModel.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnectionViewModel.kt
app/src/main/kotlin/de/hbch/traewelling/ui/user/Profile.kt
app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt
app/src/main/kotlin/de/hbch/traewelling/util/ShortcutsUtil.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

:alien: Migrate to Träwelling station IDs

---

app/src/main/kotlin/de/hbch/traewelling/ui/checkIn/CheckIn.kt

:ambulance: Fix crash when no Mastodon account is linked

---

app/src/main/kotlin/de/hbch/traewelling/api/ApiService.kt
app/src/main/kotlin/de/hbch/traewelling/api/models/report/Report.kt
app/src/main/kotlin/de/hbch/traewelling/shared/FeatureFlags.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/report/Report.kt
app/src/main/kotlin/de/hbch/traewelling/ui/report/ReportViewModel.kt
app/src/main/res/drawable/ic_announcement.xml
app/src/main/res/drawable/ic_inappropriate.xml
app/src/main/res/drawable/ic_police.xml
app/src/main/res/drawable/ic_report.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:triangular_flag_on_post: Feature flagged!

:sparkles: Add reports for statuses

---

app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/ui/activeCheckins/EnRoute.kt
app/src/main/kotlin/de/hbch/traewelling/ui/dashboard/Dashboard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/statistics/DailyStatistics.kt
app/src/main/kotlin/de/hbch/traewelling/ui/statusDetail/StatusDetail.kt
app/src/main/kotlin/de/hbch/traewelling/ui/user/Profile.kt
app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt
app/src/main/res/values-de-rDE/strings.xml

:triangular_flag_on_post: Feature flagged!

:sparkles: Enable co-travels from check-in card

---

app/src/main/kotlin/de/hbch/traewelling/api/models/status/Status.kt

:bug: Fix crash when mentioned user does not exist

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/de/hbch/traewelling/ui/login/LoginActivity.kt

:bug: Fix authentication with Firefox

---

app/build.gradle
app/src/main/kotlin/de/hbch/traewelling/api/models/notifications/Notification.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/Destinations.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/ui/composables/PushNotifications.kt
app/src/main/kotlin/de/hbch/traewelling/ui/dashboard/Dashboard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/main/MainActivity.kt
app/src/main/kotlin/de/hbch/traewelling/ui/notifications/Notifications.kt
app/src/main/kotlin/de/hbch/traewelling/util/Extensions.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

and migrate Navigation Component

:arrow_up: :recycle: Upgrade dependencies

---

app/src/main/kotlin/de/hbch/traewelling/ui/composables/SharePic.kt

:lipstick: Increase padding in SharePic dialog

---

app/build.gradle

:ambulance: Fix Dependency Block Info

---

app/src/main/kotlin/de/hbch/traewelling/ui/checkIn/CheckIn.kt
app/src/main/kotlin/de/hbch/traewelling/ui/checkInResult/CheckInResult.kt
app/src/main/kotlin/de/hbch/traewelling/ui/composables/ContentDialog.kt
app/src/main/kotlin/de/hbch/traewelling/ui/composables/ManualDateTimeSelection.kt
app/src/main/kotlin/de/hbch/traewelling/ui/composables/PushNotifications.kt
app/src/main/kotlin/de/hbch/traewelling/ui/include/status/CheckInCard.kt
app/src/main/kotlin/de/hbch/traewelling/ui/info/Info.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt
app/src/main/kotlin/de/hbch/traewelling/ui/statistics/Statistics.kt
app/src/main/kotlin/de/hbch/traewelling/ui/tag/Tag.kt
app/src/main/kotlin/de/hbch/traewelling/ui/user/TrustedUsers.kt
app/src/main/kotlin/de/hbch/traewelling/ui/user/User.kt

fixes #441 
fixes #367 
closes #439

:bug: Fix issues with date and time pickers

---

app/src/main/kotlin/de/hbch/traewelling/ui/checkIn/CheckIn.kt

:children_crossing: Remove co-traveller button when editing check-in

---

app/src/main/kotlin/de/hbch/traewelling/api/models/status/TrwlCheckInUpdateRequest.kt
app/src/main/kotlin/de/hbch/traewelling/navigation/NavHost.kt
app/src/main/kotlin/de/hbch/traewelling/shared/CheckInViewModel.kt
app/src/main/kotlin/de/hbch/traewelling/shared/EventViewModel.kt
app/src/main/kotlin/de/hbch/traewelling/ui/checkIn/CheckIn.kt
app/src/main/kotlin/de/hbch/traewelling/ui/main/MainActivity.kt

:sparkles: Enable editing of events

---

app/src/main/kotlin/de/hbch/traewelling/api/ApiService.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnection.kt
app/src/main/kotlin/de/hbch/traewelling/ui/searchConnection/SearchConnectionViewModel.kt
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values/strings.xml

:children_crossing: Show error when timetable API is down

---

app/src/main/kotlin/de/hbch/traewelling/shared/HexagonShape.kt
app/src/main/kotlin/de/hbch/traewelling/shared/TrapezoidShape.kt
app/src/main/kotlin/de/hbch/traewelling/ui/composables/LineIcon.kt

- adds shared HexagonShape
- adds shared TrapezoidShape
- adds custom shapes to LineIcon
Related: https://github.com/Traewelling/line-colors/issues/27

feat: support complex shapes

---

app/src/main/kotlin/de/hbch/traewelling/ui/checkIn/CheckIn.kt

:poop: Disable travelynx for now

---

app/src/main/kotlin/de/hbch/traewelling/api/models/status/Status.kt

:zap: Improve custom emoji performance
